---
title: Jerome Tech Club
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jeromecompsci@gmail.com
description: Announcements, Resources, and Info
baseurl: 
url: http://jeromecompsci.com
github_username: jeromecompsci
markdown: kramdown
