---
title: Jerome Comp Sci Club
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jeromecompsci@gmail.com
description: Updates and more!
baseurl: "/posts"
url: http://jeromecompsci.com
github_username: jeromecompsci
markdown: kramdown
